### ISSUE TITLE
Send warning email for Payment Links without `customer_creation = "always"`

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3423] opened 2024-09-09 19:27 UTC
If there are Stripe Payment Links on an account without `customer_creation = "always"` set, which point to a Buttondown-linked PWYW product, we should send a warning email to the customer. If these payment links are used, they won't work.

**Comment by jmduke** [comment] 2024-09-14 20:34
Closing as dupe of #3360.

**Closed by jmduke** 2024-09-14 20:34 UTC
Labels: Type: Ergonomics, Module: Paid Subscriptions

**Comment by benborgers** [comment] 2024-09-14 21:39
not again

![image](https://github.com/user-attachments/assets/aa2c3b32-d50a-41d6-8e18-8f588bb4e7e8)
