### ISSUE TITLE
Single line breaks in markdown are not properly rendered

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#3135] opened 2024-07-28 00:34 UTC
Markdown's standard stipulates that one single line break should not be rendered, only two or more should be rendered as a break between paragraphs. Our rendering pipeline recently started treating single line breaks as paragraph breaks, in contrast to the previous behavior. 

https://secure.helpscout.net/conversation/2663386411/5044/

**Comment by jmduke** [comment] 2024-09-17 19:41
Closing as dupe of https://github.com/buttondown/roadmap/issues/3118.

**Closed by jmduke** 2024-09-17 19:41 UTC
Labels: Type: Bug, Module: Outbound Email
