### ISSUE TITLE
Disabling "Enable paid subscriptions?" does not persist after Save

### ISSUE THREAD

**Issue by efletch** [buttondown/roadmap#2552] opened 2024-03-15 01:06 UTC
https://secure.helpscout.net/conversation/2540274833/3605

Steps to reproduce
* Have an account with Enable Paid Subscriptions? turned on
* Toggle "Enable Paid Subscriptions?" off
* Click Save change in bottom toolbar
* Green Updated Settings message shows and "Enable Paid Subscriptions?" appears off
* Refresh the page
* "Enable Paid Subscriptions?" shows as on

**Comment by jmduke** [comment] 2024-03-17 01:37
Closing as dupe of https://github.com/buttondown/roadmap/issues/2400.

**Closed by jmduke** 2024-03-17 01:37 UTC
Labels: bug, Monetization
