### ISSUE TITLE
Premium saved as Public

### ISSUE THREAD

**Issue by Ben-EvergreenS** [buttondown/roadmap#3437] opened 2024-09-10 19:38 UTC
[Link to Ticket](https://secure.helpscout.net/conversation/2704020719/5527?folderId=7228473)
[Link to Ticket](https://secure.helpscout.net/conversation/2699727649/5473/)

User marks emails to go out as Premium, but when they set them to schedule/finalize the email, they show as Public. Workaround is to adjust it after the change and it goes out as expected.

**Comment by jmduke** [comment] 2024-09-14 20:35
Closing as dupe of #3404.

**Closed by jmduke** 2024-09-14 20:35 UTC
Labels: Type: Bug, Module: Outbound Email
