### ISSUE TITLE
Updating description on sent email doesn't update archives index

### ISSUE THREAD

**Issue by benborgers** [buttondown/roadmap#2565] opened 2024-03-20 12:32 UTC
I've seen a couple reports that changing the newsletter description after it's been sent and then saving does not update the description on the Modern archives' index, but it does update on the email itself. 

Example:

![image](https://github.com/buttondown/roadmap/assets/30215449/5ea9c229-7169-4dd8-84da-91de119d2f07)

https://secure.helpscout.net/conversation/2544223890/3665

**Comment by jmduke** [comment] 2024-03-20 13:54
This is a dupe of https://github.com/buttondown/roadmap/issues/2440, though on a meta note: it's weird that we use `rendered_short_description` for the first screenshot and just `description` for the latter.

**Closed by jmduke** 2024-03-20 13:54 UTC
